version: 1
disable_existing_loggers: false
formatters:
  short:
    format: "%(levelname)s - %(message)s"
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: short
    stream: ext://sys.stdout
loggers:
  __main__: 
    level: INFO
    handlers:
      - console
    propagate: false
root:
  level: INFO
