name: Deploy Lambda to prod environment

on:
  push:
    branches:
      - main
    paths:
      - Lambda/**
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy-lambda.yml
    with:
      lambdaFunctionName: misskey-weather-bot-lambda-prod
      ecrRepoName: lambda/misskey-weather-bot
    secrets:
      awsDeploymentRoleArn: ${{secrets.AWS_DEPLOYMENT_ROLE_ARN_PROD}}
